version: "3.9"

services:
  gha-status-proxy:
    image: ghastatusproxy:latest
    build:
      context: .
      dockerfile: src/GhaStatusProxy/Dockerfile
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:8080"
      CONFIG_PATH: "/data/config.json"
      CONFIG_JSON: |
        {
          "Token": "ghp_replace_me",
          "Repos": [
            "owner/repo1",
            "owner/repo2"
          ]
        }
    entrypoint: >
      /bin/sh -lc '
      mkdir -p /data &&
      printf "%s" "$CONFIG_JSON" > /data/config.json &&
      cp /data/config.json /app/config.json &&
      exec /app/GhaStatusProxy'
    volumes:
      - gha_status_data:/data
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  gha_status_data:
