name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write
  packages: write

jobs:
  ci:
    name: Build & Test (.NET)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore
        run: dotnet restore src/GhaStatusProxy/GhaStatusProxy.csproj

      - name: Build
        run: dotnet build -c Release --no-restore src/GhaStatusProxy/GhaStatusProxy.csproj

      - name: Test
        run: dotnet test -c Release --no-build --verbosity normal

  docker:
    name: Build & Push Docker (GHCR)
    runs-on: ubuntu-latest
    needs: ci
    env:
      IMAGE_NAME: gha-status-proxy
      REGISTRY: ghcr.io
      OWNER: ${{ github.repository_owner }}
      VERSION: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push (multi-arch)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: src/GhaStatusProxy/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
            ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.IMAGE_NAME }}:latest
